### PR TITLE
Zack branch

### PR DESCRIPTION
**Pull request by Zackjw70**
We did our best but it didnt work

Week 4 Lab

### CODE REVIEW

**Comment by Zackjw70** [comment]
Midterm added aswell before merge 

https://github.com/Zackjw70/React/assets/122393232/693b24e4-cd9b-4ac4-8e68-ed3b0dcc9a7f

**Comment by Zackjw70** [comment]
Added Week 6 Redux follow along

https://github.com/Zackjw70/React/assets/122393232/606297f3-a646-4706-9f96-9eea01c3ff90

**Comment by Zackjw70** [comment]
Week 7 in class assignment

**Comment by Zackjw70** [comment]
Week 7 Lab assignment

https://github.com/Zackjw70/React/assets/122393232/55b9ac6f-d0d8-448a-9cce-b9cc18565379

**Comment by isaaccolson** [comment]
This looks great Zack!

**Pull request merged**
